import java.util.Scanner;

public class que2 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        System.out.print("Enter energy generated by the solar pannel(in kilo whatt hour 'kWh'): ");
        double energy = sc.nextDouble();

        if (energy >= 10.00) {
            System.out.println("Good Energy Generation");
        } else if (energy <= 10.00) {
            System.out.println("Low Energy Generation");
        } else 
            System.out.println("invalid input ");

            sc.close();
    }
}
